/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#ffdad6',
        'tertiary-container': '#8ab0ff',
        'error': '#ffb4ab',
        'surface-container-low': '#181b25',
        'on-primary-fixed-variant': '#653e00',
        'on-secondary-container': '#006b41',
        'on-error': '#690005',
        'surface-bright': '#353943',
        'on-background': '#dfe2ef',
        'secondary': '#cfffdd',
        'inverse-primary': '#855300',
        'surface-container-lowest': '#0a0e17',
        'outline-variant': '#534434',
        'primary-fixed-dim': '#ffb95f',
        'background': '#0f131c',
        'surface-dim': '#0f131c',
        'surface-variant': '#31353f',
        'secondary-fixed-dim': '#00e38f',
        'outline': '#a08e7a',
        'inverse-surface': '#dfe2ef',
        'on-surface': '#dfe2ef',
        'on-secondary-fixed': '#002111',
        'tertiary': '#b6ccff',
        'on-primary': '#472a00',
        'surface-container-highest': '#31353f',
        'primary-container': '#f59e0b',
        'secondary-container': '#03f59b',
        'on-tertiary-container': '#00408f',
        'on-tertiary-fixed': '#001a42',
        'on-primary-fixed': '#2a1700',
        'surface-tint': '#ffb95f',
        'on-secondary': '#003920',
        'primary-fixed': '#ffddb8',
        'error-container': '#93000a',
        'surface-container': '#1c1f29',
        'tertiary-fixed': '#d8e2ff',
        'on-primary-container': '#613b00',
        'tertiary-fixed-dim': '#adc6ff',
        'surface': '#0f131c',
        'surface-container-high': '#262a34',
        'on-tertiary-fixed-variant': '#004395',
        'secondary-fixed': '#53ffab',
        'on-secondary-fixed-variant': '#005231',
        'on-surface-variant': '#d8c3ad',
        'inverse-on-surface': '#2c303a',
        'on-tertiary': '#002e6a',
        'primary': '#ffc174',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'margin-desktop': '1.5rem',
        'space-sm': '0.5rem',
        'gutter-desktop': '1rem',
        'gutter': '0.75rem',
        'space-lg': '1rem',
        'space-xs': '0.25rem',
        'margin': '0.75rem',
        'space-xl': '1.5rem',
        'space-md': '0.75rem',
        'space-2xl': '2rem',
      },
      fontFamily: {
        'display-lg': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'metric-lg': ['JetBrains Mono'],
        'headline-lg': ['Space Grotesk'],
        'headline-sm': ['Space Grotesk'],
        'headline-lg-mobile': ['Space Grotesk'],
        'code-telemetry': ['JetBrains Mono'],
        'metric-xl': ['JetBrains Mono'],
        'body-lg': ['JetBrains Mono'],
        'body-md': ['JetBrains Mono'],
        'label-caps': ['JetBrains Mono'],
        'body-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '52px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'metric-lg': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'code-telemetry': ['10px', { lineHeight: '12px', letterSpacing: '0.04em', fontWeight: '400' }],
        'metric-xl': ['36px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'body-md': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '500' }],
        'body-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}